version: '3'

services:
  xreds:
    container_name: xreds
    build:
        context: .
        args:
        - WORKERS=1
    volumes:
      - "./datasets:/opt/xreds/datasets"
    restart: on-failure
    platform: linux/amd64
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - DATASETS_MAPPING_FILE=/opt/xreds/datasets/datasets.json
      - EXPORT_THRESHOLD=600
