version: '3'

services:
  xreds:
    image: xreds:latest
    platform: linux/amd64
    volumes:
      - "./datasets:/opt/xreds/datasets"
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - datasets_mapping_file=/opt/xreds/datasets/datasets.json
