version: '3'

services:
  xreds: 
    container_name: xreds
    build: .
    volumes:
      - "./datasets:/opt/xreds/datasets"
    ports: 
      - "8090:8090"
    environment:
      - PORT=8090
      - datasets_mapping_file=/opt/xreds/datasets/datasets.json
