version: '3'

services:
  nginx: 
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "8090:80"
    expose: 
      - 8090
    depends_on: 
      - xreds
  xreds: 
    container_name: xreds
    build: .
    volumes:
      - "./datasets:/opt/xreds/datasets"
    ports: 
      - "8091:8091"
    environment:
      - PORT=8091
      - ROOT_PATH=:8090
      - datasets_mapping_file=/opt/xreds/datasets/datasets.json
