apiVersion: apps/v1
kind: Deployment
metadata:
  name: xreds
  labels:
    app: xreds
spec:
  replicas: 8
  selector:
    matchLabels:
      app: xreds
  template:
    metadata:
      labels:
        app: xreds
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: xreds
      containers:
        - name: xreds
          image: public.ecr.aws/m2c5k9c1/nextgen-dmac/xreds:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: ROOT_PATH
              value: "/xreds/"
            - name: EXPORT_THRESHOLD
              value: "500"
            - name: WORKERS
              value: "1"
            - name: DATASETS_MAPPING_FILE
              value: "s3://nextgen-dmac/kerchunk/datasets.json"
            - name: MEMORY_CACHE_NUM_DATASETS
              value: "4"
            - name: USE_MEMORY_CACHE
              value: "true"
            - name: USE_REDIS_CACHE
              value: "true"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: 4Gi
            limits:
              memory: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: xreds-service
  labels:
    app: xreds
spec:
  selector:
    app: xreds
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
